colorscheme desert

set t_vb=

" ウインドウの幅
set columns=120
" ウインドウの高さ
set lines=52

" マウスに関する設定:
set mouse=a
" マウスの移動でフォーカスを自動的に切替えない (mousefocus:切替る)
set nomousefocus
" 入力時にマウスポインタを隠す (nomousehide:隠さない)
set mousehide
" ビジュアル選択(D&D他)を自動的にクリップボードへ (:help guioptions_a)
set guioptions+=a

" フォント
set antialias
" ツールバーを非表示
set guioptions-=T

" 全角文字を全角表示
set ambiwidth=double

if IsWindows()
  "IME状態に応じたカーソル色を設定
  if has('multi_byte_ime')
    highlight Cursor guifg=#000d18 guibg=#8faf9f gui=bold
    highlight CursorIM guifg=NONE guibg=#ff0000
  end
  " 透明度を指定
  autocmd guienter * set transparency=220
  " フォント
  set guifont=MeiryoKe_Console:h10
  set guifontwide=MeiryoKe_Console:h10

elseif IsMac()
  " 透明度を指定
  set transparency=20
  " フォント
  set guifont=Ricty\ Discord:h14
  set guifontwide=Ricty\ Discord:h14

endif
