[[plugins]]
repository = 'Shougo/neomru.vim'
on_ft = 'all'

[[plugins]]
repository = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'

  [plugins.on_cmd]
  name = [ 'Unite', 'UniteWithBufferDir' ]
  complete = 'customlist,unite#complete_source'

[[plugins]]
repository = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repository = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
explorer = 1

  [plugins.on_cmd]
  name = [ 'VimFiler', 'VimFilerBufferDir' ]

[[plugins]]
repository = 'Shougo/unite-help'
depends = 'Shougo/unite.vim'

[[plugins]]
repository = 'Shougo/unite-outline'
on_unite = 'outline'

[[plugins]]
repository = 'szw/vim-tags'

  [plugins.on_cmd]
  name = 'TagsGenerate'

[[plugins]]
repository = 'tpope/vim-endwise'
filetypes = 'ruby'

[[plugins]]
repository = 'tyru/open-browser.vim'
filetypes = 'all'

[[plugins]]
repository = 'thinca/vim-quickrun'
filetypes = 'all'

[[plugins]]
repository = 'hail2u/vim-css3-syntax'
filetypes = 'css'

[[plugins]]
repository = 'othree/html5.vim'
filetypes = 'html'

[[plugins]]
repository = 'pangloss/vim-javascript'
filetypes = 'javascript'

[[plugins]]
repository = 'osyo-manga/vim-brightest'
filetypes = 'all'

[[plugins]]
repository = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repository = 'https://raw.githubusercontent.com/vimperator/vimperator-labs/master/vimperator/contrib/vim/syntax/vimperator.vim'
script_type = 'syntax'
name = 'vimperator-syntax'
on_ft = 'vimperator'

[[plugins]]
repository = 'vim-scripts/kwbdi.vim'
on_map = '<Plug>Kwbd'

[[plugins]]
repository = 'Shougo/neco-vim'
on_ft = 'vim'
on_i = 1
