[[plugins]]
repo = 'Shougo/neomru.vim'
on_ft = 'all'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'

  [plugins.on_cmd]
  name = [ 'Unite', 'UniteWithBufferDir' ]
  complete = 'customlist,unite#complete_source'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
on_path = 'vimfiler.*'
on_cmd = [ 'VimFiler', 'VimFilerBufferDir' ]

[[plugins]]
repo = 'Shougo/unite-help'
depends = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_unite = 'outline'

[[plugins]]
repo = 'szw/vim-tags'

  [plugins.on_cmd]
  name = 'TagsGenerate'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'osyo-manga/vim-brightest'
on_ft = 'all'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'https://raw.githubusercontent.com/vimperator/vimperator-labs/master/vimperator/contrib/vim/syntax/vimperator.vim'
script_type = 'syntax'
name = 'vimperator-syntax'
on_ft = 'vimperator'

[[plugins]]
repo = 'vim-scripts/kwbdi.vim'
on_map = '<Plug>Kwbd'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'dzeban/vim-log-syntax'
on_ft = 'log'

[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = 'Vinarise'
