### path
## 重複したパスを登録しない。
typeset -U path
## (N-/): 存在しないディレクトリは登録しない。
##    パス(...): ...という条件にマッチするパスのみ残す。
##            N: NULL_GLOBオプションを設定。
##               globがマッチしなかったり存在しないパスを無視する。
##            -: シンボリックリンク先のパスを評価。
##            /: ディレクトリのみ残す。
case $OSTYPE in
    *darwin*)
        path=(
            # for Homebrew
            /usr/local/bin(N-/)
            /usr/local/sbin(N-/)
            $path)
        ;;
esac

### manpath
typeset -U manpath
case $OSTYPE in
    *darwin*)
        manpath=(
            $manpath)
        ;;
esac

## エディタの設定: vimを使う
export EDITOR=vim
## vimがなくてもvimでviを起動する。
if ! type vim > /dev/null 2>&1; then
    alias vim=vi
fi

### Debian 系の alias
if [ -f /etc/debian_version ]; then
    alias ls='ls --group-directories-first --color=always'
    alias acs='apt-cache search'
    alias acshow='apt-cache show'
fi

### fpath
fpath=(
    $HOME/.zsh.d/site_functions
    $fpath)

### rbenv
if type rbenv > /dev/null 2>&1; then
  eval "$(rbenv init -)"
fi
