# Path to your oh-my-zsh configuration.
ZSH=$HOME/.zsh.d/public_repos/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rbenv)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

## Emacsキーバインドを使う
bindkey -e

# ヒストリーの設定
HISTFILE=$HOME/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt share_history
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS

# 環境によってプロンプトの色を変える + 環境固有の alias の設定
env_color="$fg_bold[white]"
case $OSTYPE in
    *darwin*)
        env_color="$fg_bold[red]"
        alias lc='launchctl'
        ;;
esac

PROMPT='$(git_prompt_info)%{$env_color%}%% %{$reset_color%}'
RPROMPT='[%/]'
ZSH_THEME_GIT_PROMPT_PREFIX="git:("
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY=")%{$fg_bold[yellow]%}!%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=") "

# C-p/C-nで履歴検索 + カーソルを行末に移動
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey '' history-beginning-search-backward-end
bindkey '' history-beginning-search-forward-end

# 共通の alias の設定
alias t='ls -lhtr'
alias l='ls -lha'
alias a='ls -a'
alias f=ls
alias d=cd

alias hisg='fc -l 1 | grep'
alias tm='tmux attach || tmux'
alias e='emacsclient -n'

alias bundle='nocorrect bundle'
alias be='bundle exec'

alias gst='git status -s -b'

## 補完侯補をメニューから選択する。
### select=2: 補完候補を一覧から選択する。
###           ただし、補完候補が2つ以上なければすぐに補完する。
zstyle ':completion:*:default' menu select=2

## git のルートディレクトリに移動する cf. http://d.hatena.ne.jp/mzp/20090711/git
gd() {
    emulate -RL zsh

    if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        cd $PWD/$(git rev-parse --show-cdup)
    fi
}

## z.sh (cd 履歴を補完するコマンド) cf. http://project-p.jp/halt/?p=1724
_Z_CMD=j
source ~/.zsh.d/public_repos/z/z.sh
precmd() {
  _z --add "$(pwd -P)"
}

## auto-fu
#source ~/.zsh.d/public_repos/auto-fu.zsh/auto-fu.zsh
#zle-line-init () {auto-fu-init;}
#zle -N zle-line-init
#zstyle ':completion:*' completer _oldlist _complete

## ページャ
if type -p lv > /dev/null; then
    export PAGER="lv"
    ## -c: ANSIエスケープシーケンスの色付けなどを有効にする。
    ## -l: 1行が長くと折り返されていても1行として扱う。
    ##     （コピーしたときに余計な改行を入れない。）
    export LV="-c -l"
else
    ## lvがなくてもlvでページャーを起動する。
    alias lv="$PAGER"
fi

## ssh-agent
if [ -z "`ps -u $USER | grep ssh-agent`" ]; then
    ssh-agent > ~/.ssh/env
fi
if [ -f ~/.ssh/env ]; then
    source ~/.ssh/env > /dev/null
fi
